import React, { createContext, useState, useContext, useEffect } from 'react'

// ============================================================
// COMPLETE TRANSLATIONS
// ============================================================
const translations = {
  bm: {
    // ========== COMMON / NAVIGATION ==========
    'dashboard': 'Papan Pemuka',
    'pos': 'POS',
    'kitchen': 'Dapur',
    'manage_menu': 'Urus Menu',
    'manage_categories': 'Urus Kategori',
    'manage_staff': 'Urus Kakitangan',
    'manage_tables': 'Urus Meja',
    'table_qrs': 'QR Meja',
    'system_settings': 'Tetapan Sistem',
    'reports': 'Laporan',
    'light_mode': 'Mod Terang',
    'dark_mode': 'Mod Gelap',
    'logout': 'Log Keluar',
    'english': 'English',
    'bahasa': 'Bahasa Melayu',
    'loading': 'Memuatkan...',
    
    // ========== LOGIN PAGE ==========
    'welcome_back': 'Selamat Datang Kembali!',
    'sign_in_continue': 'Sila log masuk untuk teruskan',
    'username': 'Nama Pengguna',
    'password': 'Kata Laluan',
    'login': 'Log Masuk',
    'logging_in': 'Log masuk...',
    'login_title': 'Sistem POS untuk Restoran Kecil & Sederhana',
    'enter_username': 'Masukkan nama pengguna',
    'enter_password': 'Masukkan kata laluan',
    'username_password_required': 'Nama pengguna dan kata laluan diperlukan',
    'invalid_credentials': 'Nama pengguna atau kata laluan salah',
    'welcome': 'Selamat datang',
    'login_error': 'Ralat log masuk',
    'demo_credentials': 'Kredensial Demo',
    'login_footer': 'Sistem POS Restoran',
    'password_min_length': 'Kata laluan perlulah sekurang-kurangnya 6 aksara',
    'password_optional': 'Kata laluan (biarkan kosong jika tidak mahu tukar)',
    'password_required': 'Kata laluan diperlukan',
    'confirm_password': 'Sahkan kata laluan',
    'new_password': 'Kata laluan baru',
    'confirm_new_password': 'Sahkan kata laluan baru',
    'not_match': 'tidak sepadan',
    'already_exists': 'sudah wujud',
    'required': 'diperlukan',
    'confirm_delete': 'Anda pasti mahu padam',
    'error_updating': 'Ralat mengemaskini',
    'no_orders_to_complete': 'Tiada pesanan untuk diselesaikan',
    'confirm_complete_all': 'Selesaikan semua {count} pesanan?',
    'orders_completed': 'pesanan diselesaikan',
    'complete_all': 'Selesaikan Semua',
    'order_updated': 'Pesanan dikemaskini',
    
    // ========== TRACK ORDER ==========
    'track_title': 'Jejak Pesanan Anda',
    'track_subtitle': 'Masukkan nombor pesanan untuk semak status',
    'enter_order': 'Masukkan nombor pesanan',
    'searching': 'Mencari...',
    'track': 'Jejak',
    'order_not_found': 'Pesanan tidak dijumpai',
    'check_order': 'Sila semak nombor pesanan anda',
    'order_found': 'Pesanan dijumpai!',
    'enter_order_error': 'Sila masukkan nombor pesanan',
    'error_loading': 'Ralat memuat pesanan. Sila cuba lagi.',
    'order_type': 'Jenis Pesanan',
    'customer': 'Pelanggan',
    'order_items': 'Item Pesanan',
    'total': 'Jumlah',
    'estimated_time': 'Anggaran Masa Siap',
    'almost_ready': 'Hampir siap!',
    'refresh_status': 'Muat Semula Status',
    'auto_refresh': 'Muat semula automatik',
    'order': 'Pesanan',
    'at': 'pada',
    'table': 'Meja',
    'take_away': 'Bungkus',
    'dine_in': 'Makan di sini',
    'guest': 'Tetamu',
    'note': 'Nota',
    'pending': 'Menunggu',
    'preparing': 'Sedang Disiapkan',
    'ready': 'Sedia',
    'completed': 'Selesai',
    'cancelled': 'Dibatalkan',
    'received': 'Diterima',
    'order_again': 'Pesan Lagi →',
    'auto_complete_info': 'Pesanan akan siap secara automatik dalam ~',
    'minutes': 'minit',
    'pending_desc': 'Pesanan anda telah diterima dan menunggu pengesahan dari dapur.',
    'preparing_desc': 'Pesanan anda sedang disediakan di dapur.',
    'ready_desc': 'Pesanan anda sedia! Sila datang ke kaunter.',
    'completed_desc': 'Pesanan selesai. Terima kasih!',
    'cancelled_desc': 'Pesanan ini telah dibatalkan.',
    'unknown_desc': 'Status tidak diketahui.',
    'step_received': 'Diterima',
    'step_preparing': 'Disiapkan',
    'step_ready': 'Sedia',
    'step_completed': 'Selesai',
    
    // ========== STAFF APP ==========
    'service_charge': 'Caj Perkhidmatan',
    'tax': 'Cukai',
    'unpaid': 'Belum Bayar',
    'new_order': 'Pesanan Baru',
    'cart': 'Keranjang',
    'empty_cart': 'Keranjang kosong',
    'place_order': 'Hantar Pesanan',
    'record_payment': 'Rekod Bayaran',
    'payment_method': 'Kaedah Bayaran',
    'cash': 'Tunai',
    'tng': 'Touch n Go',
    'bank': 'Pindahan Bank',
    'subtotal': 'Jumlah Kecil',
    'add': 'Tambah',
    'edit': 'Ubah',
    'delete': 'Padam',
    'save': 'Simpan',
    'cancel': 'Batal',
    'close': 'Tutup',
    'print': 'Cetak',
    'search': 'Cari',
    'staff': 'Kakitangan',
    'accept': 'Terima',
    'date': 'Tarikh',
    'id': 'ID',
    'status': 'Status',
    'history': 'Sejarah',
    'btn_save': 'Simpan',
    'activate': 'Aktifkan',
    'promotions': 'Promosi',
    'name': 'Nama',
    'price': 'Harga',
    'type': 'Jenis',
    'image': 'Gambar',
    'description': 'Keterangan',
    'in_stock': 'Ada Stok',
    'select_size': 'Pilih Saiz',
    'choose_size': 'Pilih saiz / pilihan',
    'drink_type': 'Pilih jenis minuman',
    'hot': 'Panas',
    'cold': 'Sejuk',
    'takeaway_drink': 'Bungkus',
    'add_to_cart': 'Tambah ke Keranjang',
    'added': 'Ditambah!',
    'buy_promo': 'Beli Promo',
    'promo': 'PROMOSI',
    'size': 'Saiz',
    'table_required': 'Sila masukkan nombor meja',
    'order_sent': 'Pesanan dihantar ke dapur!',
    'data_refreshed': 'Data telah direfresh!',
    'start_cooking': 'Mula memasak!',
    'order_accepted': 'Pesanan diterima! Sedia untuk bayar.',
    'new_orders_alert': 'Klik untuk proses',
    'no_new_orders': 'Tiada pesanan baru',
    'no_unpaid': 'Tiada pesanan belum bayar',
    'no_history': 'Tiada sejarah',
    'payment_received': 'Bayaran diterima',
    'test_sound': 'Uji Bunyi',
    'grand_total': 'Jumlah Keseluruhan',
    'copied': 'Disalin!',
    
    // ========== KITCHEN APP ==========
    'kitchen_title': 'Dapur',
    'kitchen_subtitle': 'Urus Pesanan Makanan & Minuman',
    'new_orders': 'Pesanan Baru',
    'preparing_orders': 'Sedang Masak',
    'ready_orders': 'Sedia',
    'completed_orders': 'Selesai',
    'start_cooking': 'Mula Masak',
    'finish_cooking': 'Siap Masak',
    'complete': 'Selesai',
    'waiting': 'Menunggu',
    'minutes_short': 'min',
    'hours_short': 'j',
    'just_now': 'Baru sahaja',
    'food_kitchen': 'Makanan',
    'drink_kitchen': 'Minuman',
    'no_food_orders': 'Tiada Pesanan Makanan',
    'no_drink_orders': 'Tiada Pesanan Minuman',
    'no_preparing_orders': 'Tiada Pesanan Sedang Dimasak',
    'no_ready_orders': 'Tiada Pesanan Sedia',
    'no_completed_orders': 'Tiada Pesanan Selesai',
    'search_orders': 'Cari pesanan...',
    'sound': 'Bunyi',
    'refresh': 'Segar Semula',
    'process_immediately': 'Sila proses segera',
    'sound_on': 'Bunyi: ON',
    'sound_off': 'Bunyi: OFF',
    'cooking_started': 'Mula memasak!',
    'cooking_finished': 'Selesai memasak!',
    'order_completed': 'Pesanan selesai!',
    'order_cancelled': 'Pesanan dibatalkan!',
    'confirm_complete_all': 'Selesaikan semua pesanan?',
    'all_orders': 'Semua',
    
    // ========== MANAGE STAFF ==========
    'add_staff': 'Tambah Kakitangan',
    'reset_password': 'Reset Kata Laluan',
    'kitchen_staff': 'Dapur',
    'admin': 'Pentadbir',
    'full_name': 'Nama Penuh',
    'pos_access': 'Akses POS',
    'kitchen_access': 'Akses Dapur',
    'full_access': 'Akses Penuh',
    'cannot_delete_admin': 'Tidak boleh padam admin',
    'cannot_delete_self': 'Tidak boleh padam diri sendiri',
    'staff_added': 'Kakitangan berjaya ditambah',
    'staff_updated': 'Kakitangan berjaya dikemaskini',
    'staff_deleted': 'Kakitangan berjaya dipadam',
    'password_reset_success': 'Kata laluan berjaya direset',
    'manage_staff_desc': 'Urus kakitangan dan akses sistem restoran anda',
    'search_staff': 'Cari kakitangan...',
    'staff_found': 'kakitangan dijumpai',
    'no_staff': 'Tiada kakitangan',
    'edit_staff': 'Edit Kakitangan',
    'min_6_chars': 'min 6 aksara',
    'cannot_change_role': 'Tidak boleh menukar peranan sendiri',
    'reset': 'Reset',
    'access': 'Akses',
    'both_access': 'POS & Dapur',
    'pos_only': 'POS Sahaja',
    'kitchen_only': 'Dapur Sahaja',
    'full_access_role': 'Akses Penuh',
    'stats_total_staff': 'Jumlah Kakitangan',
    'stats_admin': 'Pentadbir',
    'stats_kitchen_access': 'Akses Dapur',
    'stats_pos_staff': 'Staf POS',
    'team_access': 'Pasukan & Akses',
    'team_subtitle': 'Urus kakitangan restoran dan kawalan akses sistem',
    'add_staff_title': 'Tambah Staff',
    'edit_staff_title': 'Edit Staff',
    'reset_password_title': 'Reset Kata Laluan',
    'reset_password_for': 'Reset kata laluan untuk',
    'password_required': 'Kata laluan diperlukan!',
    'password_min_length': 'Kata laluan sekurang-kurangnya 6 aksara!',
    'cannot_delete_admin': 'Tidak boleh hapus akaun admin!',
    'cannot_delete_self': 'Anda tidak boleh hapus akaun sendiri!',
    'select_access': 'Pilih aplikasi yang boleh diakses oleh kakitangan ini',
    
    // ========== MANAGE MENU ==========
    'regular_menu': 'Menu Biasa',
    'special_menu': 'Menu Istimewa',
    'add_regular_menu': 'Tambah Menu Biasa',
    'add_drink': 'Tambah Minuman',
    'select_category': 'Pilih Kategori',
    'uploading': 'Sedang muat naik...',
    'stock': 'Stok',
    'low_stock_alert': 'Amaran Stok Rendah',
    'out_of_stock': 'Habis Stok',
    'left': 'lagi',
    'menu_added': 'Item menu ditambah!',
    'menu_updated': 'Item menu dikemaskini!',
    'menu_deleted': 'Item menu dipadam!',
    'special_added': 'Item istimewa ditambah!',
    'special_updated': 'Item istimewa dikemaskini!',
    'special_deleted': 'Item istimewa dipadam!',
    'promo_added': 'Promosi ditambah!',
    'promo_updated': 'Promosi dikemaskini!',
    'promo_deleted': 'Promosi dipadam!',
    'promo_disabled': 'Promosi dilumpuhkan!',
    'promo_enabled': 'Promosi diaktifkan!',
    'order_updated': 'Urutan menu dikemaskini!',
    'category_order_updated': 'Urutan kategori dikemaskini!',
    'image_deleted': 'Gambar dipadam!',
    'image_delete_fail': 'Gagal padam gambar!',
    'upload_fail': 'Muat naik gagal!',
    'upload_success': 'Muat naik berjaya',
    'invalid_price': 'Sila masukkan harga yang sah!',
    'drink_added': 'Minuman berjaya ditambah!',
    'option_added': 'Pilihan saiz ditambah!',
    'option_updated': 'Pilihan saiz dikemaskini!',
    'option_deleted': 'Pilihan saiz dipadam!',
    'drag_hint': 'Seret untuk susun',
    'no_menu': 'Tiada item menu',
    'showing': 'Menunjukkan',
    'of': 'daripada',
    'items': 'item',
    'activate_special': 'Aktifkan Menu Istimewa',
    'activate_special_desc': 'Paparkan menu istimewa di laman utama',
    'special_title': 'Tajuk Menu Istimewa',
    'special_items': 'Item Istimewa',
    'no_special_items': 'Tiada item istimewa. Klik "Tambah" untuk mula.',
    'add_special': 'Tambah Item Istimewa',
    'edit_special': 'Edit Item Istimewa',
    'promo_name': 'Nama Promosi *',
    'promo_type': 'Jenis Promosi',
    'set_menu': 'Set Menu',
    'bundle': 'Bundle',
    'bogo': 'Beli 1 Percuma 1',
    'trigger_item': 'Item yang Dibeli',
    'free_item': 'Item Percuma',
    'bundle_items': 'Pilih Item dalam Promosi',
    'promo_price': 'Harga Promosi (RM)',
    'start_date': 'Tarikh Mula',
    'end_date': 'Tarikh Akhir',
    'promo_image': 'Gambar Promosi',
    'no_promotions': 'Tiada promosi. Klik "Tambah Promosi" untuk mula.',
    'active': 'AKTIF',
    'inactive': 'TIDAK AKTIF',
    'disable': 'Lumpuhkan',
    'enable': 'Aktifkan',
    'select_item': '-- Pilih Item --',
    'no_items_available': 'Tiada item - tambah menu terlebih dahulu',
    'items_available': 'item tersedia. Ketik kotak untuk pilih.',
    'size_options': 'Pilihan Saiz',
    'add_size': 'Tambah Saiz Baru',
    'edit_size': 'Edit Saiz',
    'size_name': 'Nama (cth: Kecil, Sederhana, Besar)',
    'size_price': 'Harga (RM)',
    'absolute_price': 'Harga Mutlak',
    'size_list': 'Senarai Saiz',
    'no_sizes': 'Tiada pilihan saiz.',
    'add_drink_title': 'Tambah Minuman (Panas/Sejuk/Bungkus)',
    'drink_name': 'Nama Minuman',
    'hot_price': 'Harga Panas',
    'cold_price': 'Harga Sejuk',
    'takeaway_price': 'Harga Bungkus',
    'edit_menu': 'Edit Menu',
    'stock_qty': 'Kuantiti Stok',
    'has_size_options': 'Ada pilihan saiz',
    'category': 'Kategori',
    'confirm_delete': 'Sahkan Hapus',
    'confirm_delete_image': 'Adakah anda pasti mahu padam gambar ini?',
    'price_updated': 'harga dikemaskini!',
    'stock_updated_to': 'stok dikemaskini kepada',
    'menu_added_success': 'Item menu ditambah!',
    'menu_updated_success': 'Item menu dikemaskini!',
    'special_added_success': 'Item istimewa ditambah!',
    'special_updated_success': 'Item istimewa dikemaskini!',
    'promo_added_success': 'Promosi ditambah!',
    'promo_updated_success': 'Promosi dikemaskini!',
    'deleted': 'dipadam!',
    
    // ========== MANAGE CATEGORIES ==========
    'manage_categories_desc': 'Urus kategori menu untuk restoran anda',
    'search_categories': 'Cari kategori...',
    'category_name_required': 'Nama kategori diperlukan',
    'category_added': 'Kategori berjaya ditambah',
    'category_updated': 'Kategori berjaya dikemaskini',
    'category_deleted': 'Kategori berjaya dipadam',
    'edit_category': 'Edit Kategori',
    'category_not_found': 'Kategori tidak dijumpai',
    'confirm_delete_category': 'Anda pasti mahu padam kategori',
    'add_category': 'Tambah Kategori',
    'category_name': 'Nama Kategori',
    'select_icon': 'Pilih Ikon',
    'or_type': 'Atau taip',
    'sort_order': 'Susunan',
    'sort_order_desc': 'Nombor kecil akan dipaparkan dahulu',
    'cannot_delete': 'Tidak boleh padam',
    'has_items': 'mempunyai',
    'menu_items': 'item menu',
    'change_category_first': 'Tukar kategori item dahulu',
    'main_categories': 'Kategori Utama',
    'sub_categories': 'Sub Kategori',
    'main': 'Kategori Utama',
    'sub': 'Sub Kategori',
    'no_categories': 'Tiada kategori. Klik "Tambah Kategori Utama" untuk mula.',
    'no_sub_categories': 'Tiada sub kategori. Klik "Tambah Sub Kategori" untuk mula.',
    'cannot_delete_with_sub': 'Tidak boleh hapus kategori yang ada sub kategori. Hapus sub kategori dahulu.',
    'add_sub_category': 'Tambah Sub Kategori',
    'parent_category': 'Kategori Induk',
    'sub_count': 'sub kategori',
    'icon': 'Ikon',
    
    // ========== MANAGE TABLES ==========
    'manage_tables_desc': 'Tambah, edit atau padam meja restoran',
    'add_table': 'Tambah Meja',
    'edit_capacity': 'Edit Kapasiti',
    'capacity_people': 'orang',
    'capacity_question': 'Berapa ramai pelanggan yang boleh duduk di meja ini?',
    'table_exists': 'sudah wujud',
    'table_has_unpaid_orders': 'mempunyai pesanan belum selesai. Sila selesaikan dahulu.',
    'table_added': 'berjaya ditambah',
    'table_updated': 'dikemaskini',
    'table_deleted': 'berjaya dipadam',
    'status_available': 'Tersedia',
    'status_occupied': 'Diduduki',
    'status_reserved': 'Ditempah',
    'status_inactive': 'Tidak Aktif',
    'no_tables': 'Tiada meja. Klik "Tambah Meja" untuk mula.',
    'edit_capacity_for': 'Edit Kapasiti Meja',
    'select_status': 'Pilih Status',
    'table_number': 'Nombor Meja',
    'capacity': 'Kapasiti',
    'tables': 'Meja',
    'stat_available': 'Tersedia',
    'stat_occupied': 'Diduduki',
    'stat_reserved': 'Ditempah',
    'enter_table_number': 'Sila masukkan nombor meja',
    'qr_code': 'Kod QR',
    'scan_to_order': 'Scan untuk pesan',
    
    // ========== MANAGE SETTINGS ==========
    'restaurant_logo': 'Logo Restoran',
    'select_logo': 'Pilih Logo',
    'upload_failed': 'Gagal muat naik',
    'logo_uploaded': 'Logo berjaya dimuat naik',
    'logo_deleted': 'Logo berjaya dipadam',
    'delete_image': 'Padam gambar?',
    'save_error': 'Gagal menyimpan',
    'settings_saved': 'Tetapan disimpan',
    'enable_special_menu': 'Aktifkan Menu Istimewa',
    'special_menu_title': 'Tajuk Menu Istimewa',
    'business_hours': 'Waktu Operasi',
    'start': 'Mula',
    'end': 'Tamat',
    'printer_type': 'Jenis Pencetak',
    'thermal_printer': 'Pencetak Thermal',
    'a4_printer': 'Pencetak A4',
    'no_printer': 'Tiada Pencetak',
    'auto_print': 'Cetak Auto',
    'notification_sound': 'Bunyi Notifikasi',
    'kitchen_app': 'Aplikasi Dapur',
    'kitchen_on_off': 'Hidup/Matikan mod dapur digital',
    'kitchen_disabled': 'Dapur Dimatikan',
    'kitchen_disabled_desc': 'Dapur sedang dimatikan. Pesanan akan terus ke kaunter.',
    'go_to_settings': 'Pergi ke Tetapan',
    'language': 'Bahasa',
    'saving': 'Menyimpan...',
    'restaurant_name': 'Nama Restoran',
    'preview': 'Pratonton',
    'example': 'contoh',
    'login_page': 'Halaman Login',
    'welcome_text': 'Teks Selamat Datang',
    'subtitle_text': 'Teks Subtitle',
    'branding_text': 'Teks Jenama',
    'footer_text': 'Teks Footer',
    'auto_complete': 'Auto Lengkap',
    'minutes_to_complete': 'Minit untuk Auto Lengkap',
    'order_will_be_completed': 'Pesanan akan dilengkapkan secara automatik selepas X minit',
    'kitchen_disabled_auto': 'Dapur Dimatikan - Auto Complete Aktif',
    'restaurant_info': 'Maklumat Restoran',
    'tax_service': 'Cukai & Caj Perkhidmatan',
    'printing': 'Pencetakan',
    'digital_kitchen': 'Dapur Digital',
    'danger_zone': 'Zon Berbahaya',
    'save_all': 'Simpan Semua Tetapan',
    'delete_all_orders': 'Padam Semua Pesanan',
    'delete_all_menu': 'Padam Semua Menu',
    'delete_all_categories': 'Padam Semua Kategori',
    'reset_all_tables': 'Reset Semua Meja',
    'delete_all_promotions': 'Padam Semua Promosi',
    'reset_all_data': 'Reset SEMUA Data',
    'type_delete': 'Taip DELETE untuk sahkan:',
    'confirm_delete_action': 'Ya, Padam',
    
    // ========== ADMIN REPORT ==========
    'sales_report': 'Laporan Jualan',
    'sales_analysis': 'Analisis Jualan',
    'today_sales': 'Jualan Hari Ini',
    'week_sales': 'Jualan Minggu Ini',
    'month_sales': 'Jualan Bulan Ini',
    'total_sales': 'Jumlah Keseluruhan',
    'total_service_charge': 'Jumlah Caj Perkhidmatan',
    'total_tax': 'Jumlah Cukai',
    'pending_payments_warning': 'Amaran: Terdapat',
    'unpaid_orders': 'pesanan belum dibayar',
    'record_payment_staff': 'Sila rekod bayaran di halaman POS',
    'sales_trend': 'Trend Jualan',
    'last_7_days': '7 Hari Terakhir',
    'top_items': 'Item Terlaris',
    'sold': 'Terjual',
    'orders_list': 'Senarai Pesanan',
    'no_orders': 'Tiada pesanan',
    'items': 'item',
    'time': 'Masa',
    'customer_name': 'Nama Pelanggan',
    'all_orders': 'Semua Pesanan',
    'paid_status': 'Sudah Bayar',
    'unpaid_status': 'Belum Bayar',
    'showing': 'Menunjukkan',
    'of': 'daripada',
    'orders': 'pesanan',
    'export_csv': 'Eksport CSV',
    'export_excel': 'Eksport Excel',
    'export_pdf': 'Eksport PDF',
    'first': 'Pertama',
    'prev': 'Sebelum',
    'next': 'Seterusnya',
    'last': 'Terakhir',
    'chart': 'Carta',
    'last_updated': 'Kemaskini terakhir',
    'table_number': 'Nombor Meja',
    'total_orders_count': 'Jumlah Pesanan',
    'active_tables': 'Meja Aktif',
    'popular_items': 'Item Popular',
    'payment_breakdown': 'Pecahan Bayaran',
    'peak_hours': 'Waktu Sibuk',
    'top_categories': 'Kategori Teratas',
    'recent_orders': 'Pesanan Terkini',
    'refresh_data': 'Muat Semula Data',
    'summary': 'Ringkasan',
    'times': 'kali',
    'paid': 'Sudah Bayar',
    'tables': 'meja',
    'sales': 'jualan',
    'today': 'Hari Ini',
    'week': 'Minggu Ini',
    'month': 'Bulan Ini',
    'no_data': 'Tiada data',
    'loading': 'Sedang memuatkan...',
    'auto_refresh_notify': 'Data auto-refresh',
    'excel_exported': 'Excel berjaya dieksport!',
    'pdf_exported': 'PDF berjaya dieksport!',
    'export_failed': 'Eksport gagal!',
    
    // ========== CUSTOMER MENU ==========
    'scan_qr': 'Imbas QR untuk pesan',
    'table_required': 'Nombor Meja Diperlukan',
    'enter_table': 'Masukkan No. Meja',
    'please_enter_table': 'Sila masukkan nombor meja untuk mula memesan',
    'order_confirmed': 'Pesanan Dikonfirmasi!',
    'order_sent_to_kitchen': 'Pesanan anda telah dihantar ke dapur',
    'order_number_label': 'Nombor Pesanan:',
    'copy': 'Salin',
    'new_order_btn': 'Pesanan Baru',
    'your_order': 'Pesanan Anda',
    'cart_empty': 'Keranjang kosong',
    'service': 'Perkhidmatan',
    'tax_label': 'Cukai',
    'total_label': 'Jumlah',
    'your_name': 'Nama anda',
    'phone_optional': 'Telefon (pilihan)',
    'special_notes': 'Catatan khas...',
    'back_to_menu': 'Kembali ke Menu',
    'please_enter_table_first': 'Sila masuk meja',
    'select_temperature': 'Pilih suhu',
    'hot': 'Panas',
    'cold': 'Sejuk',
    'add_to_cart_btn': 'Tambah ke Keranjang',
    'confirm_order_title': 'Sahkan Pesanan',
    'confirm_order_desc': 'Sila semak semula pesanan anda sebelum menghantar',
    'table_label': 'Meja:',
    'customer_label': 'Pelanggan:',
    'total_items_label': 'Jumlah Item:',
    'total_payment_label': 'Jumlah Bayaran:',
    'back_btn': 'Kembali',
    'close_btn': 'Tutup',
    'confirm_btn': 'Sahkan',
    'active_promotions': 'Promosi Giat!',
    'buy': 'Beli',
    'get': 'dapat',
    'free': 'percuma',
    'save_discount': 'Jimat',
    'only': 'Hanya',
    'added': 'Ditambah',
    'buy_promo': 'Beli Promo',
    'add_item': 'Tambah',
    'promo_badge': 'PROMO',
    'please_review': 'Sila semak semula pesanan anda',
    'order_sent': 'Pesanan Dihantar!',
    'order_sent_desc': 'Pesanan anda telah dihantar ke dapur.',
    'find_menu': 'Cari menu...',
    'menu_billing': 'Menu & Bil',
    'billing': 'Bil',
    'select_table': 'Pilih Meja',
    'find_order': 'Cari pesanan...',
    'btn_print': 'Cetak',
    'btn_pay': 'Bayar',
    'btn_receipt': 'Resit',
    'payment_received': 'Bayaran diterima',
    'thank_you': 'Terima kasih',
    'receipt_footer': 'Sila simpan resit ini untuk rujukan',
    'print_all': 'Cetak Semua',
    'promo_bundle': 'Tawaran Bundle',
    'promo_set': 'Set Menu',
    'promo_bogo': 'Beli 1 Percuma 1',
    'special_today': 'Istimewa Hari Ini',
    'add_special': 'Istimewa',
    'no_menu_category': 'Tiada menu dalam kategori ini',
    'select_size_btn': 'Pilih Saiz',
    'size_emoji': 'Saiz',
    
    // ========== CUSTOMER DISPLAY ==========
    'menu_pricing': 'Menu & Harga',
    'open': 'BUKA',
    'closed': 'TUTUP',
    'all': 'Semua',
    'billing': 'Bil',
    'all_orders': 'Semua Pesanan',
    'no_orders': 'Tiada pesanan',
    'print_all': 'Cetak Semua',
    'find_order': 'Cari pesanan...',
    'btn_print': 'Cetak',
    'btn_pay': 'Bayar',
    'btn_receipt': 'Resit',
    'payment_received': 'Bayaran diterima',
    'record_payment': 'Rekod Bayaran',
    'payment_method': 'Kaedah Bayaran',
    'cash': 'Tunai',
    'tng': 'Touch n Go',
    'bank': 'Pindahan Bank',
    'subtotal': 'Jumlah Kecil',
    'service_charge': 'Caj Perkhidmatan',
    'tax': 'Cukai',
    'total': 'Jumlah',
    'table_number': 'Nombor Meja',
    'take_away': 'Bungkus',
    'dine_in': 'Makan di sini',
    'guest': 'Tetamu',
    'thank_you': 'Terima kasih',
    'receipt_footer': 'Sila simpan resit ini untuk rujukan',
    'btn_save': 'Simpan',
    'cancel': 'Batal',
    'close': 'Tutup',
    'select_table': 'Pilih Meja',
    'print': 'Cetak',
    'promotions': 'Promosi',
    'in_stock': 'Ada Stok',
  },
  
  en: {
    // ========== COMMON / NAVIGATION ==========
    'dashboard': 'Dashboard',
    'pos': 'POS',
    'kitchen': 'Kitchen',
    'manage_menu': 'Manage Menu',
    'manage_categories': 'Manage Categories',
    'manage_staff': 'Manage Staff',
    'manage_tables': 'Manage Tables',
    'table_qrs': 'Table QR',
    'system_settings': 'System Settings',
    'reports': 'Reports',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'logout': 'Logout',
    'english': 'English',
    'bahasa': 'Bahasa Melayu',
    'loading': 'Loading...',
    
    // ========== LOGIN PAGE ==========
    'welcome_back': 'Welcome Back!',
    'sign_in_continue': 'Please sign in to continue',
    'username': 'Username',
    'password': 'Password',
    'login': 'Login',
    'logging_in': 'Logging in...',
    'login_title': 'POS System for Small & Medium Restaurants',
    'enter_username': 'Enter username',
    'enter_password': 'Enter password',
    'username_password_required': 'Username and password required',
    'invalid_credentials': 'Invalid username or password',
    'welcome': 'Welcome',
    'login_error': 'Login error',
    'demo_credentials': 'Demo Credentials',
    'login_footer': 'Restaurant POS System',
    'password_min_length': 'Password must be at least 6 characters',
    'password_optional': 'Password (leave blank to keep current)',
    'password_required': 'Password required',
    'confirm_password': 'Confirm password',
    'new_password': 'New password',
    'confirm_new_password': 'Confirm new password',
    'not_match': 'do not match',
    'already_exists': 'already exists',
    'required': 'required',
    'confirm_delete': 'Are you sure you want to delete',
    'error_updating': 'Error updating',
    'no_orders_to_complete': 'No orders to complete',
    'confirm_complete_all': 'Complete all {count} orders?',
    'orders_completed': 'orders completed',
    'complete_all': 'Complete All',
    'order_updated': 'Order updated',
    
    // ========== TRACK ORDER ==========
    'track_title': 'Track Your Order',
    'track_subtitle': 'Enter your order number to check status',
    'enter_order': 'Enter order number',
    'searching': 'Searching...',
    'track': 'Track',
    'order_not_found': 'Order not found',
    'check_order': 'Please check your order number',
    'order_found': 'Order found!',
    'enter_order_error': 'Please enter an order number',
    'error_loading': 'Error loading order. Please try again.',
    'order_type': 'Order Type',
    'customer': 'Customer',
    'order_items': 'Order Items',
    'total': 'Total',
    'estimated_time': 'Estimated Ready Time',
    'almost_ready': 'Almost ready!',
    'refresh_status': 'Refresh Status',
    'auto_refresh': 'Auto-refresh status',
    'order': 'Order',
    'at': 'at',
    'table': 'Table',
    'take_away': 'Take Away',
    'dine_in': 'Dine In',
    'guest': 'Guest',
    'note': 'Note',
    'pending': 'Pending',
    'preparing': 'Preparing',
    'ready': 'Ready',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'received': 'Received',
    'order_again': '🍽️ Order Again →',
    'auto_complete_info': 'Order will be auto completed in ~',
    'minutes': 'minutes',
    'pending_desc': 'Your order has been received and waiting for confirmation.',
    'preparing_desc': 'Your order is being prepared in the kitchen.',
    'ready_desc': 'Your order is ready! Please proceed to counter.',
    'completed_desc': 'Order completed. Thank you!',
    'cancelled_desc': 'This order has been cancelled.',
    'unknown_desc': 'Status unknown.',
    'step_received': 'Received',
    'step_preparing': 'Preparing',
    'step_ready': 'Ready',
    'step_completed': 'Completed',
    
    // ========== STAFF APP ==========
    'service_charge': 'Service Charge',
    'tax': 'Tax',
    'unpaid': 'Unpaid',
    'new_order': 'New Order',
    'cart': 'Cart',
    'empty_cart': 'Cart is empty',
    'place_order': 'Place Order',
    'record_payment': 'Record Payment',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'tng': 'Touch n Go',
    'bank': 'Bank Transfer',
    'subtotal': 'Subtotal',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'print': 'Print',
    'search': 'Search',
    'staff': 'Staff',
    'accept': 'Accept',
    'date': 'Date',
    'id': 'ID',
    'status': 'Status',
    'history': 'History',
    'btn_save': 'Save',
    'activate': 'Activate',
    'promotions': 'Promotions',
    'name': 'Name',
    'price': 'Price',
    'type': 'Type',
    'image': 'Image',
    'description': 'Description',
    'in_stock': 'In Stock',
    'select_size': 'Select Size',
    'choose_size': 'Choose size / option',
    'drink_type': 'Select drink type',
    'hot': 'Hot',
    'cold': 'Cold',
    'takeaway_drink': 'Takeaway',
    'add_to_cart': 'Add to Cart',
    'added': 'Added!',
    'buy_promo': 'Buy Promo',
    'promo': 'PROMO',
    'size': 'Size',
    'table_required': 'Please enter your table number',
    'order_sent': 'Order sent to kitchen!',
    'data_refreshed': 'Data refreshed!',
    'start_cooking': 'Started cooking!',
    'order_accepted': 'Order accepted! Ready for payment.',
    'new_orders_alert': 'Click to process',
    'no_new_orders': 'No new orders',
    'no_unpaid': 'No unpaid orders',
    'no_history': 'No history',
    'payment_received': 'Payment received',
    'test_sound': 'Test Sound',
    'grand_total': 'Grand Total',
    'copied': 'Copied!',
    
    // ========== KITCHEN APP ==========
    'kitchen_title': 'Kitchen',
    'kitchen_subtitle': 'Manage Food & Drink Orders',
    'new_orders': 'New Orders',
    'preparing_orders': 'Preparing',
    'ready_orders': 'Ready',
    'completed_orders': 'Completed',
    'start_cooking': 'Start Cooking',
    'finish_cooking': 'Finish Cooking',
    'complete': 'Complete',
    'waiting': 'Waiting',
    'minutes_short': 'min',
    'hours_short': 'hrs',
    'just_now': 'Just now',
    'food_kitchen': 'Food',
    'drink_kitchen': 'Drinks',
    'no_food_orders': 'No Food Orders',
    'no_drink_orders': 'No Drink Orders',
    'no_preparing_orders': 'No Preparing Orders',
    'no_ready_orders': 'No Ready Orders',
    'no_completed_orders': 'No Completed Orders',
    'search_orders': 'Search orders...',
    'sound': 'Sound',
    'refresh': 'Refresh',
    'process_immediately': 'Please process immediately',
    'sound_on': 'Sound: ON',
    'sound_off': 'Sound: OFF',
    'cooking_started': 'Cooking started!',
    'cooking_finished': 'Cooking finished!',
    'order_completed': 'Order completed!',
    'order_cancelled': 'Order cancelled!',
    'confirm_complete_all': 'Complete all orders?',
    'all_orders': 'All',
    
    // ========== MANAGE STAFF ==========
    'add_staff': 'Add Staff',
    'reset_password': 'Reset Password',
    'kitchen_staff': 'Kitchen',
    'admin': 'Admin',
    'full_name': 'Full Name',
    'pos_access': 'POS Access',
    'kitchen_access': 'Kitchen Access',
    'full_access': 'Full Access',
    'cannot_delete_admin': 'Cannot delete admin account',
    'cannot_delete_self': 'Cannot delete your own account',
    'staff_added': 'Staff added successfully',
    'staff_updated': 'Staff updated successfully',
    'staff_deleted': 'Staff deleted successfully',
    'password_reset_success': 'Password reset successfully',
    'manage_staff_desc': 'Manage staff and access for your restaurant system',
    'search_staff': 'Search staff...',
    'staff_found': 'staff found',
    'no_staff': 'No staff',
    'edit_staff': 'Edit Staff',
    'min_6_chars': 'min 6 chars',
    'cannot_change_role': 'Cannot change own role',
    'reset': 'Reset',
    'access': 'Access',
    'both_access': 'POS & Kitchen',
    'pos_only': 'POS Only',
    'kitchen_only': 'Kitchen Only',
    'full_access_role': 'Full Access',
    'stats_total_staff': 'Total Staff',
    'stats_admin': 'Admin',
    'stats_kitchen_access': 'Kitchen Access',
    'stats_pos_staff': 'POS Staff',
    'team_access': 'Team & Access',
    'team_subtitle': 'Manage restaurant staff and system access control',
    'add_staff_title': 'Add Staff',
    'edit_staff_title': 'Edit Staff',
    'reset_password_title': 'Reset Password',
    'reset_password_for': 'Reset password for',
    'password_required': 'Password is required!',
    'password_min_length': 'Password must be at least 6 characters!',
    'cannot_delete_admin': 'Cannot delete admin account!',
    'cannot_delete_self': 'You cannot delete your own account!',
    'select_access': 'Select which apps this staff can access',
    
    // ========== MANAGE MENU ==========
    'regular_menu': 'Regular Menu',
    'special_menu': 'Special Menu',
    'add_regular_menu': 'Add Regular Menu',
    'add_drink': 'Add Drink',
    'select_category': 'Select Category',
    'uploading': 'Uploading...',
    'stock': 'Stock',
    'low_stock_alert': 'Low Stock Alert',
    'out_of_stock': 'Out of Stock',
    'left': 'left',
    'menu_added': 'Menu item added!',
    'menu_updated': 'Menu item updated!',
    'menu_deleted': 'Menu item deleted!',
    'special_added': 'Special item added!',
    'special_updated': 'Special item updated!',
    'special_deleted': 'Special item deleted!',
    'promo_added': 'Promotion added!',
    'promo_updated': 'Promotion updated!',
    'promo_deleted': 'Promotion deleted!',
    'promo_disabled': 'Promotion disabled!',
    'promo_enabled': 'Promotion enabled!',
    'order_updated': 'Menu order updated!',
    'category_order_updated': 'Category order updated!',
    'image_deleted': 'Image deleted!',
    'image_delete_fail': 'Failed to delete image!',
    'upload_fail': 'Upload failed!',
    'upload_success': 'Upload successful',
    'invalid_price': 'Please enter a valid price!',
    'drink_added': 'Drink added successfully!',
    'option_added': 'Size option added!',
    'option_updated': 'Size option updated!',
    'option_deleted': 'Size option deleted!',
    'drag_hint': 'Drag to reorder',
    'no_menu': 'No menu items',
    'showing': 'Showing',
    'of': 'of',
    'items': 'items',
    'activate_special': 'Activate Special Menu',
    'activate_special_desc': 'Display special menu on homepage',
    'special_title': 'Special Menu Title',
    'special_items': 'Special Items',
    'no_special_items': 'No special items. Click "Add" to start.',
    'add_special': 'Add Special Item',
    'edit_special': 'Edit Special Item',
    'promo_name': 'Promotion Name *',
    'promo_type': 'Promotion Type',
    'set_menu': 'Set Menu',
    'bundle': 'Bundle',
    'bogo': 'Buy 1 Free 1',
    'trigger_item': 'Purchased Item',
    'free_item': 'Free Item',
    'bundle_items': 'Select Bundle Items',
    'promo_price': 'Promotion Price (RM)',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'promo_image': 'Promotion Image',
    'no_promotions': 'No promotions. Click "Add Promotion" to start.',
    'active': 'ACTIVE',
    'inactive': 'INACTIVE',
    'disable': 'Disable',
    'enable': 'Enable',
    'select_item': '-- Select Item --',
    'no_items_available': 'No items available - add menu items first',
    'items_available': 'items available. Tap checkbox to select.',
    'size_options': 'Size Options',
    'add_size': 'Add New Size',
    'edit_size': 'Edit Size',
    'size_name': 'Name (e.g: Small, Medium, Large)',
    'size_price': 'Price (RM)',
    'absolute_price': 'Absolute Price',
    'size_list': 'Size List',
    'no_sizes': 'No size options available.',
    'add_drink_title': 'Add Drink (Hot/Cold/Takeaway)',
    'drink_name': 'Drink Name',
    'hot_price': 'Hot Price',
    'cold_price': 'Cold Price',
    'takeaway_price': 'Takeaway Price',
    'edit_menu': 'Edit Menu',
    'stock_qty': 'Stock Quantity',
    'has_size_options': 'Has size options',
    'category': 'Category',
    'confirm_delete': 'Confirm Delete',
    'confirm_delete_image': 'Are you sure you want to delete this image?',
    'price_updated': 'price updated!',
    'stock_updated_to': 'stock updated to',
    'menu_added_success': 'Menu item added!',
    'menu_updated_success': 'Menu item updated!',
    'special_added_success': 'Special item added!',
    'special_updated_success': 'Special item updated!',
    'promo_added_success': 'Promotion added!',
    'promo_updated_success': 'Promotion updated!',
    'deleted': 'deleted!',
    
    // ========== MANAGE CATEGORIES ==========
    'manage_categories_desc': 'Manage menu categories for your restaurant',
    'search_categories': 'Search categories...',
    'category_name_required': 'Category name required',
    'category_added': 'Category added successfully',
    'category_updated': 'Category updated successfully',
    'category_deleted': 'Category deleted successfully',
    'edit_category': 'Edit Category',
    'category_not_found': 'Category not found',
    'confirm_delete_category': 'Are you sure you want to delete this category',
    'add_category': 'Add Category',
    'category_name': 'Category Name',
    'select_icon': 'Select Icon',
    'or_type': 'Or type',
    'sort_order': 'Sort Order',
    'sort_order_desc': 'Smaller number appears first',
    'cannot_delete': 'Cannot delete',
    'has_items': 'has',
    'menu_items': 'menu items',
    'change_category_first': 'Change category of items first',
    'main_categories': 'Main Categories',
    'sub_categories': 'Sub Categories',
    'main': 'Main Category',
    'sub': 'Sub Category',
    'no_categories': 'No categories yet. Click "Add Main Category" to start.',
    'no_sub_categories': 'No sub categories. Click "Add Sub Category" to start.',
    'cannot_delete_with_sub': 'Cannot delete category with sub categories. Delete sub categories first.',
    'add_sub_category': 'Add Sub Category',
    'parent_category': 'Parent Category',
    'sub_count': 'sub categories',
    'icon': 'Icon',
    
    // ========== MANAGE TABLES ==========
    'manage_tables_desc': 'Add, edit or delete restaurant tables',
    'add_table': 'Add Table',
    'edit_capacity': 'Edit Capacity',
    'capacity_people': 'people',
    'capacity_question': 'How many customers can sit at this table?',
    'table_exists': 'already exists',
    'table_has_unpaid_orders': 'has unpaid orders. Please settle them first.',
    'table_added': 'added successfully',
    'table_updated': 'updated',
    'table_deleted': 'deleted successfully',
    'status_available': 'Available',
    'status_occupied': 'Occupied',
    'status_reserved': 'Reserved',
    'status_inactive': 'Inactive',
    'no_tables': 'No tables. Click "Add Table" to start.',
    'edit_capacity_for': 'Edit Table Capacity',
    'select_status': 'Select Status',
    'table_number': 'Table Number',
    'capacity': 'Capacity',
    'tables': 'Tables',
    'stat_available': 'Available',
    'stat_occupied': 'Occupied',
    'stat_reserved': 'Reserved',
    'enter_table_number': 'Please enter table number',
    'qr_code': 'QR Code',
    'scan_to_order': 'Scan to order',
    
    // ========== MANAGE SETTINGS ==========
    'restaurant_logo': 'Restaurant Logo',
    'select_logo': 'Select Logo',
    'upload_failed': 'Upload failed',
    'logo_uploaded': 'Logo uploaded successfully',
    'logo_deleted': 'Logo deleted successfully',
    'delete_image': 'Delete image?',
    'save_error': 'Failed to save',
    'settings_saved': 'Settings saved',
    'enable_special_menu': 'Enable Special Menu',
    'special_menu_title': 'Special Menu Title',
    'business_hours': 'Business Hours',
    'start': 'Start',
    'end': 'End',
    'printer_type': 'Printer Type',
    'thermal_printer': 'Thermal Printer',
    'a4_printer': 'A4 Printer',
    'no_printer': 'No Printer',
    'auto_print': 'Auto Print',
    'notification_sound': 'Notification Sound',
    'kitchen_app': 'Kitchen App',
    'kitchen_on_off': 'Turn digital kitchen mode on/off',
    'kitchen_disabled': 'Kitchen Disabled',
    'kitchen_disabled_desc': 'Kitchen is currently disabled. Orders will go directly to counter.',
    'go_to_settings': 'Go to Settings',
    'language': 'Language',
    'saving': 'Saving...',
    'restaurant_name': 'Restaurant Name',
    'preview': 'Preview',
    'example': 'example',
    'login_page': 'Login Page',
    'welcome_text': 'Welcome Text',
    'subtitle_text': 'Subtitle Text',
    'branding_text': 'Branding Text',
    'footer_text': 'Footer Text',
    'auto_complete': 'Auto Complete',
    'minutes_to_complete': 'Minutes to Auto Complete',
    'order_will_be_completed': 'Order will be auto completed after X minutes',
    'kitchen_disabled_auto': 'Kitchen Disabled - Auto Complete Active',
    'restaurant_info': 'Restaurant Info',
    'tax_service': 'Tax & Service Charge',
    'printing': 'Printing',
    'digital_kitchen': 'Digital Kitchen',
    'danger_zone': 'Danger Zone',
    'save_all': 'Save All Settings',
    'delete_all_orders': 'Delete All Orders',
    'delete_all_menu': 'Delete All Menu',
    'delete_all_categories': 'Delete All Categories',
    'reset_all_tables': 'Reset All Tables',
    'delete_all_promotions': 'Delete All Promotions',
    'reset_all_data': 'Reset ALL Data',
    'type_delete': 'Type DELETE to confirm:',
    'confirm_delete_action': 'Yes, Delete',
    
    // ========== ADMIN REPORT ==========
    'sales_report': 'Sales Report',
    'sales_analysis': 'Sales Analysis',
    'today_sales': "Today's Sales",
    'week_sales': "This Week's Sales",
    'month_sales': "This Month's Sales",
    'total_sales': 'Total Sales',
    'total_service_charge': 'Total Service Charge',
    'total_tax': 'Total Tax',
    'pending_payments_warning': 'Warning: There are',
    'unpaid_orders': 'unpaid orders',
    'record_payment_staff': 'Please record payment in POS page',
    'sales_trend': 'Sales Trend',
    'last_7_days': 'Last 7 Days',
    'top_items': 'Top Items',
    'sold': 'Sold',
    'orders_list': 'Orders List',
    'no_orders': 'No orders',
    'items': 'items',
    'time': 'Time',
    'customer_name': 'Customer Name',
    'all_orders': 'All Orders',
    'paid_status': 'Paid',
    'unpaid_status': 'Unpaid',
    'showing': 'Showing',
    'of': 'of',
    'orders': 'orders',
    'export_csv': 'Export CSV',
    'export_excel': 'Export Excel',
    'export_pdf': 'Export PDF',
    'first': 'First',
    'prev': 'Prev',
    'next': 'Next',
    'last': 'Last',
    'chart': 'Chart',
    'last_updated': 'Last updated',
    'table_number': 'Table Number',
    'total_orders_count': 'Total Orders',
    'active_tables': 'Active Tables',
    'popular_items': 'Popular Items',
    'payment_breakdown': 'Payment Breakdown',
    'peak_hours': 'Peak Hours',
    'top_categories': 'Top Categories',
    'recent_orders': 'Recent Orders',
    'refresh_data': 'Refresh Data',
    'summary': 'Summary',
    'times': 'times',
    'paid': 'Paid',
    'tables': 'tables',
    'sales': 'sales',
    'today': 'Today',
    'week': 'This Week',
    'month': 'This Month',
    'no_data': 'No data',
    'loading': 'Loading...',
    'auto_refresh_notify': 'Data auto-refreshed',
    'excel_exported': 'Excel exported successfully!',
    'pdf_exported': 'PDF exported successfully!',
    'export_failed': 'Export failed!',
    
    // ========== CUSTOMER MENU ==========
    'scan_qr': 'Scan QR to order',
    'table_required': 'Table Number Required',
    'enter_table': 'Enter Table No.',
    'please_enter_table': 'Please enter your table number to start ordering',
    'order_confirmed': 'Order Confirmed!',
    'order_sent_to_kitchen': 'Your order has been sent to the kitchen',
    'order_number_label': 'Order Number:',
    'copy': 'Copy',
    'new_order_btn': 'New Order',
    'your_order': 'Your Order',
    'cart_empty': 'Cart is empty',
    'service': 'Service',
    'tax_label': 'Tax',
    'total_label': 'Total',
    'your_name': 'Your name',
    'phone_optional': 'Phone (optional)',
    'special_notes': 'Special notes...',
    'back_to_menu': 'Back to Menu',
    'please_enter_table_first': 'Please enter table number',
    'select_temperature': 'Select temperature',
    'hot': 'Hot',
    'cold': 'Cold',
    'add_to_cart_btn': 'Add to Cart',
    'confirm_order_title': 'Confirm Order',
    'confirm_order_desc': 'Please review your order before submitting',
    'table_label': 'Table:',
    'customer_label': 'Customer:',
    'total_items_label': 'Total Items:',
    'total_payment_label': 'Total Payment:',
    'back_btn': 'Back',
    'close_btn': 'Close',
    'confirm_btn': 'Confirm',
    'active_promotions': 'Active Promotions!',
    'buy': 'Buy',
    'get': 'get',
    'free': 'free',
    'save_discount': 'Save',
    'only': 'Only',
    'added': 'Added',
    'buy_promo': 'Buy Promo',
    'add_item': 'Add',
    'promo_badge': 'PROMO',
    'please_review': 'Please review your order',
    'order_sent': 'Order Sent!',
    'order_sent_desc': 'Your order has been sent to the kitchen.',
    'find_menu': 'Find menu...',
    'menu_billing': 'Menu & Billing',
    'billing': 'Billing',
    'select_table': 'Select Table',
    'find_order': 'Find order...',
    'btn_print': 'Print',
    'btn_pay': 'Pay',
    'btn_receipt': 'Receipt',
    'payment_received': 'Payment received',
    'thank_you': 'Thank you',
    'receipt_footer': 'Please keep this receipt for reference',
    'print_all': 'Print All',
    'promo_bundle': 'Bundle Deal',
    'promo_set': 'Set Menu',
    'promo_bogo': 'Buy 1 Free 1',
    'special_today': 'Special Today',
    'add_special': 'Special',
    'no_menu_category': 'No menu items in this category',
    'select_size_btn': 'Select Size',
    'size_emoji': 'Size',
    
    // ========== CUSTOMER DISPLAY ==========
    'menu_pricing': 'Menu & Pricing',
    'open': 'OPEN',
    'closed': 'CLOSED',
    'all': 'All',
    'billing': 'Billing',
    'all_orders': 'All Orders',
    'no_orders': 'No orders',
    'print_all': 'Print All',
    'find_order': 'Find order...',
    'btn_print': 'Print',
    'btn_pay': 'Pay',
    'btn_receipt': 'Receipt',
    'payment_received': 'Payment received',
    'record_payment': 'Record Payment',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'tng': 'Touch n Go',
    'bank': 'Bank Transfer',
    'subtotal': 'Subtotal',
    'service_charge': 'Service Charge',
    'tax': 'Tax',
    'total': 'Total',
    'table_number': 'Table Number',
    'take_away': 'Take Away',
    'dine_in': 'Dine In',
    'guest': 'Guest',
    'thank_you': 'Thank you',
    'receipt_footer': 'Please keep this receipt for reference',
    'btn_save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'select_table': 'Select Table',
    'print': 'Print',
    'promotions': 'Promotions',
    'in_stock': 'In Stock',
  }
}

// ============================================================
// LANGUAGE CONTEXT
// ============================================================
const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('kedaipos-language')
    return saved || 'bm'
  })

  useEffect(() => {
    localStorage.setItem('kedaipos-language', language)
  }, [language])

  const t = (key, params = {}) => {
    let text = translations[language][key] || translations.en[key] || key
    
    // Replace params like {count}
    if (params && typeof params === 'object') {
      Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param])
      })
    }
    
    return text
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}